---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    expose: "true"
    app: config-test
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: at.liwest.esb.config-test
  name: config-test
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: config-test
