---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-commit: 4188e4448825e3aa532fc50d6aed93e68f7376c5
    fabric8.io/iconUrl: img/icons/wildfly.svg
    fabric8.io/git-branch: master
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=config-test&var-version=1.0.0-SNAPSHOT
  labels:
    app: config-test
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: at.liwest.esb.config-test
  name: config-test
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: config-test
    provider: fabric8
    group: at.liwest.esb.config-test
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 4188e4448825e3aa532fc50d6aed93e68f7376c5
        fabric8.io/iconUrl: img/icons/wildfly.svg
        fabric8.io/git-branch: master
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=config-test&var-version=1.0.0-SNAPSHOT
      labels:
        app: config-test
        provider: fabric8
        version: 1.0.0-SNAPSHOT
        group: at.liwest.esb.config-test
    spec:
      containers:
      - env:
        - name: AB_OFF
          value: "true"
        - name: AB_PROMETHEUS_OFF
          value: "true"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: config-test:latest
        imagePullPolicy: IfNotPresent
        name: config-test
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        resources:
          limits:
            cpu: "1.0"
            memory: 1024Mi
          requests:
            cpu: "0.2"
            memory: 128Mi
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          items:
          - key: config.properties
            path: config.properties
          name: config-test
        name: config
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - config-test
      from:
        kind: ImageStreamTag
        name: config-test:latest
    type: ImageChange
