---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 431f636d220b706fff1d718189203d1ec758f7b0
    fabric8.io/iconUrl: img/icons/wildfly.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: config-test
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: at.liwest.esb.config-test
  name: config-test
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: config-test
    provider: fabric8
    group: at.liwest.esb.config-test
