---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: config-test
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: config-test@sha256:9812788c94bbe7f1b1d68a59d4149148f7e94f860427941b4fb62c9c3e867ced
        namespace: configmap
      name: latest
