---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: config-test
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: config-test@sha256:b1b5aadad117f695f9a4e75bb42215feea007ad999abd690f76358a9aa6b3ffa
        namespace: test
      name: latest
