---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: config-test
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: config-test@sha256:d027c31197f8d248e8a92da81b78649ce76905ca1791539d3f4734b11290037c
        namespace: configmap
      name: latest
