---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: config-test
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: at.liwest.esb.config-test
  name: config-test
data:
  config.properties: |
    incognito.config.zipcode=900
